### ISSUE TITLE
VL53L1X_ULD support for Ardunio megaAVR Boards?

### ISSUE THREAD

**Issue by pkhardage** [rneurink/VL53L1X_ULD#2]
Great to have vl53l1x_uld support in Adding IDE but need support for Nano Every, one of the mega AVR boards. When could we expect this support?

**Comment by rneurink** [comment]
If you download the master branch and put it in your libraries folder it should work. I'll update a new release package soon with a few more examples

**Comment by pkhardage** [comment]
Thanks for the quick response. Does this include support for the


Ardunio megaAVR Boards?

**Comment by rneurink** [comment]
Yes, it will likely work. I don't have a nano every so I cannot test it but it compiles on my machine. 
You should connect D18 of the nano every to SDA on the sensor and D19 to SCL.

**Comment by pkhardage** [comment]
For some reason this email didn't make it to the issues list response.

>     ---------- Original Message ----------
>     From: pkhardage ***@***.***>
>     To: rneurink/VL53L1X_ULD ***@***.***>
>     Date: 03/18/2021 1:03 PM
>     Subject: Re: [rneurink/VL53L1X_ULD] VL53L1X_ULD support for Ardunio megaAVR Boards? (#2)
>      
>      
>     I have a working system with the XL53L1X running on a Ardunio Nano Every and using Pololu and SparkFun driver. When I try to upload your basic example it fails with error loading Nano Every.
>      
>     The Nano Every is part of the Arduino megaAVR board family. It is based on the ATMega4809 processor core.
>      
>     I, and probably others, am confused about the two libraries on GetHub.
>     The VL53L1X_ULD and the STM32duino VL53L1X. Are these the same, different? The STM32dino specifically says it supports the AVR boards but not the megaAVR boards.
>      
>     I need the ULD library running on the Nano Every for features not in the libraries I am currently using. Since I have a working Nano Every system, I can run and give feedback on any new examples you need tested. My  sensor is connected to A4-SDA and A5-SCL of the Nano Every.
>      
>     Hope this helps,   Kent Hardage
>      
>

**Comment by rneurink** [comment]
I've got it working on an Atmega4809-CNANO board from microschip with the [MegaCoreX](https://github.com/MCUdude/MegaCoreX) from mcudude.
So it actually works on the chip. Can you post the VL53L1X module you use and the wiring?

**Comment by pkhardage** [comment]
![VL53L1X Laser Ranging Module](https://user-images.githubusercontent.com/80868805/112045715-c7a2b980-8b10-11eb-8547-1de01a5db997.jpg)
Hello and thanks for your response. The sensor I am using is the VL531X-V2. Brand: Teyleten Robot purchased on Amazon.
Picture attached.  I am using Ardunio IDE with Board selected "Ardunio Nano Every" and Registers emulation: "ATMEGA328".
The Nano Every is part of the Ardunio megaAVR board family. It is based on the ATMMega4809 processor core.
My existing working system is using the VL53L1X sensor described above running on the Ardunio Nano Every and working with the Pololu or the SparkFUN VL53L1X drivers. The VL53L1X sensor is connected to A4(D18) - SDA and A5(D19) - SCL of the Nano Every.
Sounds like we may be close to success. Note I was running with Register emulation mode "ATMEGA328" ??   Maybe I don't have the correct version of the VL53L1X_ULD driver yet. Please direct me to the version you see working and I will try it out. I will give you feedback on any results. Looking forward to hearing from you.

**Comment by rneurink** [comment]
If you download the [master branch](https://github.com/rneurink/VL53L1X_ULD/archive/refs/heads/master.zip) and put it in your libraries folder it should compile and work.
You could try to disable the atmega328 register emulation to try out.

Can you run the GetVersionInfo and the ReadDistance examples?
Also it is good to verify the sensor on your board is looking like the one on the picture. There is also the VL53L0X sensor that doesn't have these gold looking glass pieces on it, but doesn't work with this library.

**Comment by pkhardage** [comment]
I verified the sensor to be L1X.  I did redownload master branch into my ardunio/libraries folder. I went to the examples to run the GetVersionInfo and also ran the ReadDistance examples. I ran each with Register emulation: "ATMEGA328" and No emulation with the same results. I always get "Error compiling for board Ardunio Nano Every".
Is it possible that the Ardunio Nano Every is not in the supported processor file of the VL53L1X_ULD driver? I am just running the compile verify not the compile upload and getting the error.

**Comment by pkhardage** [comment]
Success!!  I assumed that since you had been able to get it to work with the Atmega4809-CNANO board, I must have a problem in my location of the software in my library structure. When in the Ardunio IDE and I went to file, examples I saw all the other XL53L1X drivers and examples but not for the XL53L1X_ULD_lite driver with examples. I had just been running out of the folder with ULD examples and that did not work. The issue was that the XL53L1X_ULD Compressed(Zipped) file was downloaded into the library folder. When unzipped the files were placed one level below the library folder. Ok, so problem fixed and examples of the GetVersionInfo and the ReadDistance work. They work with either of the Registers emulation: ATMEGA328 or NONE. Interesting. 
This opens up the ability for me to investigate an interest in a narrow application of the sensor(50mm - 200mm distance with steel metal as the target). This is an area where the sensor performs poorly because of the high reflectivity of the metal.
Thanks again and did you have to make any changes to the driver or is it the one already posted and just needed to be verified? If I can help out on anything related to this issue just let me know and I will be glad to help.

**Comment by rneurink** [comment]
Ah great. I didn't have to change anything, so that's great as it works on pretty much every platform now.
I'll update the repo with some new examples soon (multi-sensor and ROI) so keep an eye out if this is interesting for you

**Comment by rneurink** [comment]
See the repo again for more examples on how to use the library, might be interesting.

**Comment by pkhardage** [comment]
Thanks, when I get some time I will have to run the new examples on the Nano Every. Thanks for the update.
